server:
  address: localhost
  port: 8082

spring:
  application:
    name: poesy-question
  datasource:
    url: jdbc:mysql://localhost:3306/poesy?useUnicode=true&characterEncoding=utf8&useSSL=false&serverTimezone=Asia/Shanghai
    username: ${MYSQL_USERNAME}
    password: ${MYSQL_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
        ip: ${EXTERNAL_IP:127.0.0.1}
