server:
  port: 8080

spring:
  main:
    web-application-type: reactive

  application:
    name: poesy-gateway

  cloud:
    nacos:
      discovery:
        server-addr: ${NACOS_SERVER_ADDRESS}

    gateway:
      discovery:
        locator:
          enabled: true

      routes:
        - id: poesy-user
          uri: lb://poesy-user
          predicates:
            - Path=/api/user/**
        - id: poesy-question
          uri: lb://poesy-question
          predicates:
            - Path=/api/question/**
        - id: poesy-article
          uri: lb://poesy-article
          predicates:
            - Path=/api/article/**
        - id: poesy-image
          uri: lb://poesy-image
          predicates:
            - Path=/api/image/**
        - id: poesy-qwen
          uri: lb://poesy-qwen
          predicates:
            - Path=/api/qwen/**
