server:
  address: localhost
  port: 8087

spring:
  application:
    name: poesy-answer
  datasource:
    url: jdbc:mysql://localhost:3306/poesy?useUnicode=true&characterEncoding=utf8&useSSL=false&serverTimezone=Asia/Shanghai
    username: ${MYSQL_USERNAME}
    password: ${MYSQL_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver
  cloud:
    nacos:
      discovery:
        server-addr: ${NACOS_SERVER_ADDRESS:127.0.0.1:8848}
        ip: ${EXTERNAL_IP:127.0.0.1}

  # jpa:
  #   hibernate:
  #     ddl-auto: update # 自动更新数据库结构
  #   properties:
  #     hibernate:
  #       dialect: org.hibernate.dialect.MySQL5Dialect
  #       show_sql: true # 开启SQL日志
