server:
  address: localhost
  port: 8081

spring:
  data:
    redis:
      host: localhost
      port: 6379
  mail:
    host: smtp.qq.com
    port: 587
    username: ${MAIL_USERNAME}
    password: ${MAIL_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
  application:
    name: poesy-user
  datasource:
    url: jdbc:mysql://localhost:3306/poesy?useUnicode=true&characterEncoding=utf8&useSSL=false&serverTimezone=Asia/Shanghai
    username: ${MYSQL_USERNAME}
    password: ${MYSQL_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver
  cloud:
    nacos:
      discovery:
        server-addr: ${NACOS_SERVER_PORT}
        ip: ${EXTERNAL_IP:127.0.0.1}
