name: Check

on:
  push:
    branches: [*]
  pull_request:
    branches: [main]

jobs:
  check:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Setup Corretto 21
        uses: actions/setup-java@v4
        with:
          distribution: 'corretto'
          java-version: 21
      - name: Build with Maven
        run: |
          cp .env.example .env
          mvn -B package --file poesy-gateway/pom.xml -DskipTests
          mvn -B package --file poesy-user/pom.xml -DskipTests
          mvn -B package --file poesy-question/pom.xml -DskipTests
          mvn -B package --file poesy-image/pom.xml -DskipTests
